---
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Build and Publish to PyPI

on:
  push:
    # Pattern matched against refs/tags
    tags:
    - '*' # Push events to every tag not containing /

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
    - name: Checkout git repository
      uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # https://github.com/marketplace/actions/publish-python-poetry-package
    - name: Publish to PyPI
      uses: JRubics/poetry-publish@v1.17
      with:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
